openapi: 3.0.3 # version of the specification 
info: 
  version: '1' 
  title: Pessoa Service
 
servers: 
  - url: http://localhost:8080 
 
paths: 
  /pessoas: 
    get: 
      summary: Retorna uma lista de pessoas
      operationId: buscarPessoas 
      responses: 
        200: 
          description: 'OK'
          content:
            application/json:
              schema: 
                type: array
                items: 
                  schema:
                    type: object 
                  properties: 
                  id:
                    type: integer
                  name:
                    type: string
                  $ref: '#/components/schemas/PessoaResponse' 
             
  /pessoas/{id}: 
    parameters: 
      - in: path 
        name: id 
        schema: 
          type: integer 
          format: int64
        required: true 
        description: "Id da pessoa" 
        example: 1 
    get: 
      summary: Busca pessoa pelo id
      operationId: buscarPessoaPeloId 
      responses: 
        200: 
          description: 'OK'
          content: 
            application/json: 
              schema: 
                $ref: '#/components/schemas/PessoaResponse' 
components: 
  schemas: 
    PessoaRequest: 
      type: object 
      properties: 
        id: 
          type: integer 
          format: int64  
        name: 
          type: string 
      example:  
        id: 1
        name: Jessica Right
    PessoaResponse: 
      type: object 
      properties: 
        id: 
          type: integer 
          format: int64  
        name: 
          type: string 
      example:  
        id: 1
        name: Jessica Right  
          
          
          